FROM python:3.12-slim

WORKDIR /app

# Install netcat for health checks
RUN apt-get update && \
    apt-get install -y netcat-traditional && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY kafka/producer.py .

RUN pip install kafka-python

CMD ["python", "producer.py"]
